### ISSUE TITLE
TestApplications failing on Go 1.7

### ISSUE THREAD

**Issue by timoreimann** [gambol99/go-marathon#194]
As can be observed on [this Travis CI build run](https://travis-ci.org/gambol99/go-marathon/builds/158021089), running all tests under Go 1.7 produces [an error](https://travis-ci.org/gambol99/go-marathon/jobs/158021092#L202-L229):

```
=== RUN   TestApplications
--- FAIL: TestApplications (0.00s)
	Error Trace:	application_test.go:265
	Error:		Received unexpected error "Marathon API error: not found"
		
	Error Trace:	application_test.go:266
	Error:		Expected value not to be nil.
		
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x48e641]

goroutine 44 [running]:
panic(0x7083c0, 0xc420014140)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420158240)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:579 +0x25d
panic(0x7083c0, 0xc420014140)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
github.com/gambol99/go-marathon.TestApplications(0xc420158240)
	/home/travis/gopath/src/github.com/gambol99/go-marathon/application_test.go:267 +0x141
testing.tRunner(0xc420158240, 0x790d40)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/gambol99/go-marathon	0.012s
make: *** [test] Error 1
```

Under Go 1.5 and 1.6, everything is working fine.

**Comment by timoreimann** [comment]
The problem is that, for no (or `nil`) `url.Values` passed to `marathon.Applications(url.Values)`, `v.Encode()` returns an empty string, leading to the query part of the URL consisting of nothing but a `?`. For Go < 1.7, `url.Parse()` (called by go-marathon indirectly through `http.NewRequest`) would silently eat the empty question mark during printing, whereas Go 1.7 keeps it unless the new `ForceQuery` parameter (enabled during parsing for the case at hand) is disabled. See also my debug commit output on Travis for [1.6](https://travis-ci.org/gambol99/go-marathon/jobs/158028431#L204) and [1.7](https://travis-ci.org/gambol99/go-marathon/jobs/158028432#L203), respectively.

Related Go issue: https://github.com/golang/go/issues/13488
